name: Check mergeability and dependencies for ghstack prs

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  pr-dependencies-check:
    runs-on: ubuntu-latest
    outputs:
      regex-match: ${{ steps.regex-match.outputs.match }}
    steps:
      - id: regex-match
        uses: actions-ecosystem/action-regex-match@d50fd2e7a37d0e617aea3d7ada663bd56862b9cc
        with:
          text: ${{ github.head_ref }}
          regex: '^(gh/[^/]+/[0-9]+/)head$'

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup git
        run: |
          git config --global user.email "pytorchmergebot@users.noreply.github.com"
          git config --global user.name "PyTorch MergeBot"
          git fetch origin main

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: pip
          architecture: x64

      - run: pip install pyyaml==6.0 rockset==1.0.3

      - name: Verify mergeability
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUM: ${{ github.event.pull_request.number }}
        run: |
          set -ex
          python3 .github/scripts/trymerge.py --check-mergeability "${PR_NUM}"

      - name: Print debug info
        if: ${{ failure() }}
        env:
          PR_NUM: ${{ github.event.pull_request.number }}
        run: |
          {
            echo "# PR $PR_NUM is not mergeable into main"
            echo "To debug, run the diagnostic workflow:"
            echo "https://github.com/pytorch/test-infra/actions/workflows/pr-dependencies-check.yml"
          } >> "$GITHUB_STEP_SUMMARY"


concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true